function plot_fv_and_power_data(varargin)
% Plots fv and power data from Excel sheet

params.data_file_string = '';
params.curves_sheet = 'prep_curves';
params.summary_sheet = 'summary_prep';
params.prep_string = '';

% Update
params = parse_pv_pairs(params,varargin);

% Code
d = read_structure_from_excel('filename',params.data_file_string, ...
        'sheet',params.curves_sheet);
    
% Extract data
fs = sprintf('f_raw_%s',params.prep_string);
f_raw = d.(fs);
fs = sprintf('v_raw_%s',params.prep_string);
v_raw = d.(fs);
fs = sprintf('p_raw_%s',params.prep_string);
p_raw = d.(fs);
fs = sprintf('fv_f_fit_%s',params.prep_string);
fv_f_fit = d.(fs);
fs = sprintf('fv_v_fit_%s',params.prep_string);
fv_v_fit = d.(fs);
fs = sprintf('pf_f_fit_%s',params.prep_string);
pf_f_fit = d.(fs);
fs = sprintf('pf_pow_fit_%s',params.prep_string);
pf_pow_fit = d.(fs);

% Pull index to appropriate summary data
d = read_structure_from_excel('filename',params.data_file_string, ...
        'sheet',params.summary_sheet);
ii = regexp(params.prep_string,'_');
prep_name = params.prep_string((ii(end)+1):end)
vi = find(strcmp(d.prep,prep_name));

% Display
figure(51);
clf;

sp = initialise_publication_quality_figure( ...
        'right_margin',1, ...
        'x_to_y_axes_ratio',2, ...
        'no_of_panels_wide',1, ...
        'no_of_panels_high',2, ...
        'axes_padding_left',1.5, ...
        'axes_padding_right',0.5, ...
        'top_margin',0.3, ...
        'axes_padding_bottom',0.3);
    
subplot(sp(1));
hold on;
plot(f_raw,v_raw,'bo');
plot(fv_f_fit,fv_v_fit,'r-');
improve_axes( ...
    'title',params.prep_string, ...
    'title_text_interpreter','none', ...
    'title_y_offset',1.15, ...
    'x_axis_label','Stress (N m^{-2})', ...
    'y_axis_label',{'Shortening','velocity','(l_0 s^{-1})'}, ...
    'x_ticks',0:5000:multiple_greater_than(max(fv_f_fit),5000), ...
    'y_ticks',0:0.5:multiple_greater_than(max(fv_v_fit),0.5), ...
    'x_tick_decimal_places',0, ...
    'y_tick_decimal_places',1, ...
    'x_axis_offset',0, ...
    'y_axis_offset',0);
display_string = sprintf('v_max: %g\nfv_a: %g\nfv_b: %g\nfv_r_squared: %g', ...
    d.fv_v_max(vi),d.fv_a(vi),d.fv_b(vi),d.fv_r_squared(vi));
x_limits=xlim;
y_limits=ylim;
text(1.3*mean(x_limits),1.3*mean(y_limits),display_string, ...
    'Interpreter','none');

subplot(sp(2));
hold on;
plot(f_raw,p_raw,'bo');
plot(pf_f_fit,pf_pow_fit,'r-');
improve_axes( ...
    'x_axis_label','Stress (N m^{-2})', ...
    'y_axis_label',{'Power','(W kg^{-1})'}, ...
    'x_ticks',0:5000:multiple_greater_than(max(pf_f_fit),5000), ...
    'y_ticks',0:0.2:multiple_greater_than(max(pf_pow_fit),0.2), ...
    'x_tick_decimal_places',0, ...
    'y_tick_decimal_places',1, ...
    'x_axis_offset',0, ...
    'y_axis_offset',0);
display_string = sprintf('pow_max: %g\npow_a: %g\npow_b: %g\npow_r_squared: %g\nrel f at max power: %g', ...
    d.pow_max(vi),d.pow_a(vi),d.pow_b(vi),d.pow_r_squared(vi),d.rel_f_at_max_power(vi));
x_limits=xlim;
y_limits=ylim;
text(1.3*mean(x_limits),1.3*mean(y_limits),display_string, ...
    'Interpreter','none');




